name: Manual Commit / Deploy (Safe)

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Falls du einen Build-Schritt hast, kommt der hier hin
      # - name: Build project
      #   run: npm install && npm run build

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Pfad zum fertigen HTML/CSS/JS — anpassen falls nötig
          path: ./mtk-portal-upload

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
