# =====================================================================
# File: .github/workflows/manual-commit.yml
# Version: v1.3 (2025-08-18)
# Change History:
# - v1.0 (2025-08-18 10:20) Initial workflow
# - v1.1 (2025-08-18 10:45) Verify + Build Timestamp (UTC)
# - v1.2 (2025-08-18 12:40) Build Info erweitert (Branch, Commit, Run)
# - v1.3 (2025-08-18 13:10) Zeitstempel: UTC **und** Europe/Berlin + Verifikations-Grep
# =====================================================================

name: Manual Commit + Deploy

on:
  workflow_dispatch:
    inputs:
      note:
        description: "Kurznotiz fürs Protokoll"
        required: false
        default: "Manual deploy"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  commit-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto-commit (optional)
        run: |
          git config --global user.name "MTK-AutoCommit"
          git config --global user.email "mtk-bot@example.com"
          git add -A
          git commit -m "Automated commit via workflow" || echo "No changes to commit"
          git push || true

      - name: Configure Pages
        uses: actions/configure-pages@v5

      # Guard: ohne index.html kein Deploy
      - name: Verify portal files exist
        run: |
          test -f mtk-portal-upload/index.html || { echo "mtk-portal-upload/index.html fehlt"; exit 1; }

      # Stempelt: UTC **und** Europe/Berlin + Branch + Commit + Run
      # Verifiziert die gestempelte Zeile via grep (fail-fast bei Abweichung)
      - name: Stamp Build Tag (UTC + Europe/Berlin) and Write Version
        env:
          BRANCH: ${{ github.ref_name }}
          SHA_FULL: ${{ github.sha }}
          RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
          NOTE: ${{ github.event.inputs.note }}
        run: |
          set -e
          ts_utc="$(date -u '+%Y-%m-%d %H:%M')Z"
          ts_berlin="$(TZ=Europe/Berlin date '+%Y-%m-%d %H:%M')"
          shortsha="${SHA_FULL:0:7}"
          f="mtk-portal-upload/index.html"

          new="Build ${ts_utc} / ${ts_berlin} Europe/Berlin · ${BRANCH} · #${shortsha} · Run ${RUN_NUMBER}"
          perl -0777 -pe "s/Build.*?(?=<)/${new}/" -i "$f"
          echo "Stamped: ${new}"

          # Verifikation im Artefakt (Pflicht): die Build-Zeile MUSS exakt so enthalten sein
          grep -nF "${new}" "$f" >/dev/null || { echo "Verifikation fehlgeschlagen: Build-Zeile nicht exakt im index.html"; exit 1; }

          # Versionierung für CM
          ver="$(date -u '+%Y.%m.%d')-${RUN_NUMBER}"
          printf "%s\n" "${ver}" > mtk-portal-upload/VERSION
          cat > mtk-portal-upload/version.json <<JSON
          {
            "version": "${ver}",
            "time_utc": "$(date -u '+%Y-%m-%dT%H:%M:00Z')",
            "time_europe_berlin": "${ts_berlin}",
            "branch": "${BRANCH}",
            "commit": "${shortsha}",
            "run_id": "${RUN_ID}",
            "run_number": ${RUN_NUMBER},
            "note": "${NOTE}"
          }
          JSON

          {
            echo "## Deploy Summary"
            echo ""
            echo "- **Stamped:** ${new}"
            echo "- **Version:** ${ver}"
            echo "- **Note:** ${NOTE}"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifact (mtk-portal-upload)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./mtk-portal-upload

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
