name: Manual Commit / Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Was soll passieren?"
        type: choice
        required: true
        default: promote-zip
        options:
          - promote-zip        # neueste uploads/*.zip → nach /portal entpacken, Redirect setzen
          - init-mvp           # minimale Portal-Dateien schreiben (index/process/metrics + CSS)
          - redirect-only      # nur Root-Redirect auf /portal/index.html schreiben
          - guideline-v1-1     # CMO_Portal_Structure_Guideline_v1.1.yaml anlegen/aktualisieren
          - commit-staged      # vorhandene Änderungen einfach committen (falls du schon Dateien editiert hast)
      commit_message:
        description: "Commit-Message"
        required: false
        default: "[MANUAL] Commit via Run workflow"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure base folders
        run: |
          mkdir -p uploads portal assets config .github/workflows

      - name: init-mvp (optional)
        if: ${{ github.event.inputs.action == 'init-mvp' }}
        run: |
          cat > index.html <<'HTML'
          <!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
          <title>MTK‑Portal</title><link rel="stylesheet" href="assets/style.css">
          <header><h1>Willkommen im MTK‑Portal</h1>
            <nav><a href="index.html">Home</a><a href="process.html">Prozesslandschaft</a><a href="metrics.html">Metriken</a></nav>
          </header>
          <main><h2>Quick‑Win MVP</h2><p>Startseite des MTK‑Portals (MVP).</p></main>
          <footer>Version 0.1 MVP · © MTK</footer></html>
          HTML
          cat > process.html <<'HTML'
          <!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
          <title>Prozesslandschaft</title><link rel="stylesheet" href="assets/style.css">
          <header><h1>Prozesslandschaft</h1>
            <nav><a href="index.html">Home</a><a href="process.html">Prozesslandschaft</a><a href="metrics.html">Metriken</a></nav>
          </header>
          <main><h2>Visuelle Darstellung</h2><p>Interaktive Stages‑Ansicht (Platzhalter).</p></main>
          <footer>Version 0.1 MVP · © MTK</footer></html>
          HTML
          cat > metrics.html <<'HTML'
          <!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
          <title>Metriken</title><link rel="stylesheet" href="assets/style.css">
          <header><h1>Metriken</h1>
            <nav><a href="index.html">Home</a><a href="process.html">Prozesslandschaft</a><a href="metrics.html">Metriken</a></nav>
          </header>
          <main><h2>CMO‑Status (Demo)</h2><ul><li>Offene Punkte: 3</li><li>Letztes Update: heute</li><li>Status: Grün</li></ul></main>
          <footer>Version 0.1 MVP · © MTK</footer></html>
          HTML
          cat > assets/style.css <<'CSS'
          body{font-family:Arial,Helvetica,sans-serif;margin:0}
          header{background:#003366;color:#fff;padding:12px;text-align:center}
          nav a{color:#fff;margin:0 10px;text-decoration:none}
          main{padding:20px}
          footer{background:#f0f0f0;text-align:center;padding:10px;font-size:.85em}
          CSS

      - name: redirect-only (optional)
        if: ${{ github.event.inputs.action == 'redirect-only' }}
        run: |
          cat > index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=./portal/index.html">
          <title>MTK‑Portal lädt…</title>
          <p>Weiter zu <a href="./portal/index.html">MTK‑Portal</a>.</p>
          HTML

      - name: guideline-v1-1 (optional)
        if: ${{ github.event.inputs.action == 'guideline-v1-1' }}
        run: |
          mkdir -p config
          cat > config/CMO_Portal_Structure_Guideline_v1.1.yaml <<'YAML'
          owner: CMO
          status: active
          structure:
            root: [index.html, README.md, .github/workflows, portal, uploads, docs, assets, config, archive]
          naming:
            zips: mtk-portal-static-<version>.zip
            latest_alias: mtk-portal-static-latest.zip
          deployment:
            source: github-actions
            redirect_root: /portal/index.html
          controls:
            releases: tag-required
            checksum: sha256-required
            changelog: required
          YAML

      - name: promote-zip (optional)
        if: ${{ github.event.inputs.action == 'promote-zip' }}
        run: |
          set -e
          sudo apt-get update -y && sudo apt-get install -y unzip rsync
          LATEST_ZIP=$(ls -t uploads/*.zip | head -n 1)
          echo "Using ZIP: $LATEST_ZIP"
          rm -rf portal
          mkdir -p portal
          unzip -o "$LATEST_ZIP" -d portal
          # Root-Redirect, damit / auf /portal/ zeigt
          cat > index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <meta http-equiv="refresh" content="0; url=./portal/index.html">
          <title>MTK‑Portal lädt…</title>
          HTML

      - name: Commit & Push
        run: |
          git config user.name "mtk-portal-bot"
          git config user.email "bot@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "${{ github.event.inputs.commit_message }}"
            git push origin HEAD:${{ github.ref_name }}
          fi

      - name: Build & Deploy Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
