# =====================================================================
# File: .github/workflows/manual-commit.yml
# Version: v1.4 (2025-08-18)
# Change History:
# - v1.0 Initial workflow
# - v1.1 Verify + Build Timestamp (UTC)
# - v1.2 Build Info erweitert (Branch, Commit, Run)
# - v1.3 Zeitstempel UTC+Berlin + strenge Verifikation (failed)
# - v1.4 Regex-Anpassung für robuste Ersetzung + Verifikation gefixt
# =====================================================================

name: Manual Commit + Deploy

on:
  workflow_dispatch:
    inputs:
      note:
        description: "Kurznotiz fürs Protokoll"
        required: false
        default: "Manual deploy"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  commit-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auto-commit (optional)
        run: |
          git config --global user.name "MTK-AutoCommit"
          git config --global user.email "mtk-bot@example.com"
          git add -A
          git commit -m "Automated commit via workflow" || echo "No changes to commit"
          git push || true

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Verify portal files exist
        run: |
          test -f mtk-portal-upload/index.html || { echo "mtk-portal-upload/index.html fehlt"; exit 1; }

      - name: Stamp Build Tag (UTC + Europe/Berlin) and Write Version
        env:
          BRANCH: ${{ github.ref_name }}
          SHA_FULL: ${{ github.sha }}
          RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
          NOTE: ${{ github.event.inputs.note }}
        run: |
          set -e
          ts_utc="$(date -u '+%Y-%m-%d %H:%M')Z"
          ts_berlin="$(TZ=Europe/Berlin date '+%Y-%m-%d %H:%M')"
          shortsha="${SHA_FULL:0:7}"
          f="mtk-portal-upload/index.html"

          new="Build ${ts_utc} / ${ts_berlin} Europe/Berlin · ${BRANCH} · #${shortsha} · Run ${RUN_NUMBER}"

          # Robuste Ersetzung: nur den alten Build-Zeitstempel-Block ersetzen
          perl -0777 -pe "s/Build [^\n<]+/${new}/" -i "$f"
          echo "Stamped: ${new}"

          # Verifikation
          if ! grep -qF "${new}" "$f"; then
            echo "Verifikation fehlgeschlagen: '${new}' nicht in index.html"
            exit 1
          fi

          # Versionierungsdateien
          ver="$(date -u '+%Y.%m.%d')-${RUN_NUMBER}"
          printf "%s\n" "${ver}" > mtk-portal-upload/VERSION
          cat > mtk-portal-upload/version.json <<JSON
          {
            "version": "${ver}",
            "time_utc": "$(date -u '+%Y-%m-%dT%H:%M:00Z')",
            "time_europe_berlin": "${ts_berlin}",
            "branch": "${BRANCH}",
            "commit": "${shortsha}",
            "run_id": "${RUN_ID}",
            "run_number": ${RUN_NUMBER},
            "note": "${NOTE}"
          }
          JSON

          {
            echo "## Deploy Summary"
            echo ""
            echo "- **Stamped:** ${new}"
            echo "- **Version:** ${ver}"
            echo "- **Note:** ${NOTE}"
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifact (mtk-portal-upload)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./mtk-portal-upload

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
